# Generated by Django 3.0.4 on 2020-04-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OperationsApp', '0006_auto_20200331_1121'),
        ('ContentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_ref', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=25)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('remarks', models.CharField(max_length=256)),
                ('reconcile_status_bool', models.BooleanField(default=False, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='AccountsApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('trip_bool', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TripPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('inout_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=25)),
                ('description', models.CharField(choices=[('NONE', 'Please Select Description'), ('CUSTOMERIN', 'Customer In-Payment'), ('CUSTOMERREF', 'Customer Refund'), ('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('HOTEL', 'Hotel'), ('VISA', 'Visa'), ('TI', 'Travel Insurance'), ('LP', 'Land Package'), ('FERRY', 'Ferry'), ('BUS', 'Bus'), ('COMMOUT', 'Commission Paid'), ('COMMIN', 'Commission Received')], default='NONE', max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='OperationsApp.Booking')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='AccountsApp.Transaction')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='ContentApp.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='AccountsApp.TransactionHead'),
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ProformaInvoice', to='OperationsApp.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('inout_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=25)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PendingPayments', to='OperationsApp.Booking')),
                ('proforma_invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='PendingPayments', to='AccountsApp.ProformaInvoice')),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='PendingPayments', to='ContentApp.Vendor')),
            ],
        ),
    ]
