# Generated by Django 3.0.4 on 2020-04-24 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountsApp', '0001_initial'),
        ('OperationsApp', '0001_initial'),
        ('ContentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='OperationsApp.Booking'),
        ),
        migrations.AddField(
            model_name='trippayment',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='AccountsApp.TripPaymentHead'),
        ),
        migrations.AddField(
            model_name='trippayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='AccountsApp.Transaction'),
        ),
        migrations.AddField(
            model_name='trippayment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='ContentApp.Vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='AccountsApp.Account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='AccountsApp.TransactionHead'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PendingPayments', to='OperationsApp.Booking'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PendingPayments', to='ContentApp.Vendor'),
        ),
    ]
