# Generated by Django 3.0.4 on 2020-04-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0001_initial'),
        ('AccountsApp', '0002_auto_20200412_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trippayment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='ContentApp.Vendor'),
        ),
    ]
