# Generated by Django 3.0.4 on 2020-04-14 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0003_auto_20200412_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPaymentHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], default='VENDOR', max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='trippayment',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TripPayments', to='AccountsApp.TripPaymentHead'),
        ),
    ]
