# Generated by Django 3.0.4 on 2020-04-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0004_auto_20200414_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reconcile_details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
