# Generated by Django 3.0.4 on 2020-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0005_transaction_reconcile_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='inout_type',
        ),
    ]
