# Generated by Django 3.0.4 on 2020-04-15 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0007_auto_20200414_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippayment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
