# Generated by Django 3.0.4 on 2020-05-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0002_traveler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveler',
            old_name='issue_Date',
            new_name='issue_date',
        ),
    ]
