# Generated by Django 3.0.4 on 2020-05-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0003_auto_20200530_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='travelers',
            field=models.ManyToManyField(to='ProfilesApp.Traveler'),
        ),
    ]
