# Generated by Django 3.0.4 on 2020-04-24 05:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[('WORLD', 'World'), ('IND', 'India'), ('EUR', 'Europe'), ('EASTEUR', 'Eastern Europe'), ('SA', 'South Asia'), ('NA', 'North Asia'), ('CA', 'Central Asia'), ('AFR', 'Africa'), ('AM', 'Americas'), ('ME', 'Middle East'), ('SCND', 'Scandinavia'), ('CRUISE', 'Cruise')], default='WORLD', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('destinations', models.ManyToManyField(related_name='Vendors', to='ContentApp.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('transfer_type', models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared')], max_length=255)),
                ('description', models.TextField()),
                ('max_pax', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transfers', to='ContentApp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Sightseeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Sightseeing', to='ContentApp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Hotels', to='ContentApp.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Cities', to='ContentApp.Destination'),
        ),
    ]
