# Generated by Django 3.0.4 on 2020-04-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='destination',
        ),
    ]
