# Generated by Django 3.0.4 on 2020-04-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='price',
            new_name='adult_price',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='destination',
        ),
        migrations.AddField(
            model_name='insurance',
            name='destinations',
            field=models.ManyToManyField(related_name='Insurances', to='ContentApp.Destination'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurer',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='child_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='destinations',
            field=models.ManyToManyField(related_name='Visas', to='ContentApp.Destination'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='coverage',
            field=models.PositiveIntegerField(),
        ),
    ]
