# Generated by Django 3.0.4 on 2020-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0003_auto_20200427_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightseeing',
            name='adult_cutoff_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='child_cutoff_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='max_pax',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
