# Generated by Django 3.0.4 on 2020-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0005_auto_20200430_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='adult_cutoff_age',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='visa',
            name='child_cutoff_age',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
