# Generated by Django 3.0.4 on 2020-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0006_auto_20200430_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='adult_cutoff_age',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='visa',
            name='child_cutoff_age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
