# Generated by Django 3.0.4 on 2020-05-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0008_sightseeing_tour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('starting_place', models.CharField(max_length=100)),
                ('hotel_options', models.TextField(blank=True)),
                ('cities', models.ManyToManyField(to='ContentApp.City')),
                ('destinations', models.ManyToManyField(to='ContentApp.Destination')),
            ],
        ),
    ]
