# Generated by Django 3.0.4 on 2020-05-03 08:56

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0009_fixedpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpackage',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixedpackage',
            name='hotel_options',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=100, size=None),
        ),
        migrations.CreateModel(
            name='FPItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRANSPORT', 'Transport'), ('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('VISA', 'Visa'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=50)),
                ('day_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('airline', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('transport_type', models.CharField(blank=True, choices=[('TRAIN', 'Train'), ('BUS', 'Bus'), ('FERRY', 'Ferry'), ('TAXI', 'Taxi'), ('CAR', 'Self Drive Car Rental')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('freeze_inclusion', models.BooleanField()),
                ('freeze_day', models.BooleanField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.City')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Insurance')),
                ('sightseeing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Sightseeing')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Transfer')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Visa')),
            ],
        ),
    ]
