# Generated by Django 3.0.4 on 2020-05-04 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0011_auto_20200503_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('valid_from_date', models.DateField(default=datetime.date.today)),
                ('valid_till_date', models.DateField()),
                ('pricing_type', models.CharField(choices=[('FLAT', 'Flat pricing per adult / child'), ('PAXWISE', 'Pricing by total number of pax')], default='FLAT', max_length=50)),
                ('flat_adult_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('flat_child_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adult_cutoff_age', models.PositiveSmallIntegerField(default=2)),
                ('child_cutoff_age', models.PositiveSmallIntegerField(default=1)),
                ('paxwise_max_pax_list', models.CharField(blank=True, max_length=50)),
                ('paxwise_price_list', models.CharField(blank=True, max_length=100)),
                ('season_pricing_bool', models.BooleanField(default=False)),
                ('season_cutoff_dates', models.CharField(blank=True, max_length=100)),
                ('season_adult_price_factors', models.CharField(blank=True, max_length=100)),
                ('season_child_price_factors', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='fpitem',
            old_name='freeze_day',
            new_name='default_exclude',
        ),
        migrations.RenameField(
            model_name='fpitem',
            old_name='freeze_inclusion',
            new_name='optional',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='max_pax',
        ),
        migrations.AlterField(
            model_name='fixedpackage',
            name='hotel_options',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='adult_cutoff_age',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='child_cutoff_age',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='SHARED', max_length=255),
        ),
        migrations.AlterField(
            model_name='visa',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='visa',
            name='child_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('transport_class', models.CharField(choices=[('TRAIN', 'Train'), ('BUS', 'Bus'), ('FERRY', 'Ferry'), ('TAXI', 'Taxi'), ('CAR', 'Self Drive Car Rental')], max_length=50)),
                ('transport_type', models.CharField(choices=[('PRIVATE', 'With Private Transfers'), ('SHARED', 'With Shared Transfers')], default='SHARED', max_length=50)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adult_cutoff_age', models.PositiveSmallIntegerField(default=2)),
                ('child_cutoff_age', models.PositiveSmallIntegerField(default=1)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transports_From_City', to='ContentApp.City')),
                ('from_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transports_From_Destination', to='ContentApp.Destination')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transports_To_City', to='ContentApp.City')),
                ('to_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transports_To_Destination', to='ContentApp.Destination')),
            ],
        ),
    ]
