# Generated by Django 3.0.4 on 2020-05-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0012_auto_20200504_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpitem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fpitem',
            name='fixed_package',
        ),
        migrations.RemoveField(
            model_name='fpitem',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='fpitem',
            name='sightseeing',
        ),
        migrations.RemoveField(
            model_name='fpitem',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='fpitem',
            name='visa',
        ),
        migrations.AddField(
            model_name='sightseeing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='visa',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='FixedPackage',
        ),
        migrations.DeleteModel(
            name='FPItem',
        ),
    ]
