# Generated by Django 3.0.4 on 2020-05-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0014_auto_20200505_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='name',
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='SHARED', max_length=50),
        ),
    ]
