# Generated by Django 3.0.4 on 2020-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0015_auto_20200505_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightseeing',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
