# Generated by Django 3.0.4 on 2020-05-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0016_auto_20200505_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
