# Generated by Django 3.0.4 on 2020-05-07 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0042_auto_20200507_1654'),
        ('ContentApp', '0017_transport_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='season_adult_price_factors',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='season_child_price_factors',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='season_cutoff_dates',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='season_pricing_bool',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='adult_cutoff_age',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='child_cutoff_age',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='sightseeing',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='adult_cutoff_age',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='child_cutoff_age',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='price',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='adult_cutoff_age',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='child_cutoff_age',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='visa',
            name='price',
        ),
        migrations.AddField(
            model_name='pricing',
            name='inclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pricings', to='SalesApp.Inclusion'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pricings', to='ContentApp.Insurance'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pricings', to='SalesApp.Package'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='sightseeing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pricings', to='ContentApp.Sightseeing'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pricings', to='ContentApp.Transfer'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pricings', to='ContentApp.Transport'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pricings', to='ContentApp.Visa'),
        ),
        migrations.AddField(
            model_name='transport',
            name='variable_pricing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='valid_till_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
