# Generated by Django 3.0.4 on 2020-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0018_auto_20200507_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='variable_pricing',
            field=models.BooleanField(default=False),
        ),
    ]
