# Generated by Django 3.0.4 on 2020-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0019_auto_20200507_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
