# Generated by Django 3.0.4 on 2020-05-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0020_pricing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Transport'),
        ),
    ]
