# Generated by Django 3.0.4 on 2020-05-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0042_auto_20200507_1654'),
        ('ContentApp', '0021_auto_20200507_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='inclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Inclusion'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Insurance'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Package'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='sightseeing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Sightseeing'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Transfer'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Visa'),
        ),
    ]
