# Generated by Django 3.0.4 on 2020-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0022_auto_20200507_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='destinations',
            field=models.ManyToManyField(to='ContentApp.Destination'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='flat_adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='flat_child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
