# Generated by Django 3.0.4 on 2020-05-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0023_auto_20200508_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='insurer',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='destinations',
        ),
    ]
