# Generated by Django 3.0.4 on 2020-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0025_tag_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(blank=True, upload_to='tag_images/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, upload_to='theme_images/'),
        ),
    ]
