# Generated by Django 3.0.4 on 2020-04-21 11:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('id_at_source', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('ARCHIVED', 'Archived'), ('LEAD', 'Lead Created')], default='NEW', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
