# Generated by Django 3.0.4 on 2020-04-24 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MarketingApp', '0001_initial'),
        ('ContentApp', '0001_initial'),
        ('ProfilesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='AssignedInquiries', to='ProfilesApp.Staff'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Inquiries', to='ProfilesApp.Staff'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='Inquiries', to='ContentApp.Destination'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Inquiries', to='MarketingApp.LeadSource'),
        ),
    ]
