# Generated by Django 3.0.4 on 2020-04-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0001_initial'),
        ('MarketingApp', '0002_auto_20200421_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, editable=False, related_name='Inquiries', to='ProfilesApp.Staff'),
        ),
    ]
