# Generated by Django 3.0.4 on 2020-04-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0001_initial'),
        ('MarketingApp', '0003_auto_20200422_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Inquiries', to='ProfilesApp.Staff'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='AssignedInquiries', to='ProfilesApp.Staff'),
        ),
    ]
