# Generated by Django 3.0.4 on 2020-04-24 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
        ('SalesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cities', models.ManyToManyField(related_name='Quotes', to='ContentApp.City')),
                ('destinations', models.ManyToManyField(related_name='Quotes', to='ContentApp.Destination')),
                ('hotels', models.ManyToManyField(related_name='Quotes', to='ContentApp.Hotel')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Quotes', to='SalesApp.Lead')),
                ('sightseeings', models.ManyToManyField(related_name='Quotes', to='ContentApp.Sightseeing')),
                ('transfers', models.ManyToManyField(related_name='Quotes', to='ContentApp.Transfer')),
            ],
        ),
    ]
