# Generated by Django 3.0.4 on 2020-04-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0001_initial'),
        ('SalesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Leads', to='ProfilesApp.Staff'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='AssignedLeads', to='ProfilesApp.Staff'),
        ),
    ]
