# Generated by Django 3.0.4 on 2020-03-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='IN17000', editable=False, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Leads', to='SalesApp.Customer'),
        ),
    ]
