# Generated by Django 3.0.4 on 2020-04-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
        ('SalesApp', '0002_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='destinations',
        ),
        migrations.AddField(
            model_name='quote',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Quotes', to='ContentApp.Destination'),
        ),
    ]
