# Generated by Django 3.0.4 on 2020-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
        ('SalesApp', '0003_auto_20200424_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='destination',
        ),
        migrations.AddField(
            model_name='quote',
            name='destinations',
            field=models.ManyToManyField(related_name='Quotes', to='ContentApp.Destination'),
        ),
    ]
