# Generated by Django 3.0.4 on 2020-04-26 04:34

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
        ('SalesApp', '0004_auto_20200424_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='adults',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='children',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='children_age',
            field=django_mysql.models.ListCharField(models.IntegerField(), default=3, max_length=20, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='starting_place',
            field=models.CharField(default='Mumbai', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuoteBasics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField()),
                ('children_age', django_mysql.models.ListCharField(models.IntegerField(), max_length=20, size=None)),
                ('title', models.CharField(max_length=100)),
                ('starting_place', models.CharField(max_length=100)),
                ('cities', models.ManyToManyField(to='ContentApp.City')),
                ('destinations', models.ManyToManyField(to='ContentApp.Destination')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SalesApp.Lead')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('no_of_rooms', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.City')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Hotel')),
            ],
        ),
    ]
