# Generated by Django 3.0.4 on 2020-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0005_lead_trip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('FNF', 'Friends & Family'), ('TT', 'Travel Triangle'), ('CRF', 'Customer Referral'), ('RPC', 'Repeat Customer')], default='FNF', max_length=256),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('NEW', 'New Enquiry'), ('QUOTED', 'Quoted'), ('BOOKED', 'Booked')], default='NEW', max_length=25),
        ),
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
