# Generated by Django 3.0.4 on 2020-03-27 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0006_auto_20200326_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('FNF', 'Friends & Family'), ('TT', 'Travel Triangle'), ('CRF', 'Customer Referral'), ('RPC', 'Repeat Customer'), ('FBAD', 'Facebook Ads'), ('B2B', 'B2B'), ('WEB', 'Website / Online Forums')], default='FNF', max_length=256),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source_id',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
