# Generated by Django 3.0.4 on 2020-03-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0007_auto_20200327_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(blank=True, default='IN17000', editable=False, max_length=10),
        ),
    ]
