# Generated by Django 3.0.4 on 2020-04-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0008_auto_20200426_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotehotelinfo',
            name='checkin_date',
            field=models.DateField(default='2020-05-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotehotelinfo',
            name='checkout_date',
            field=models.DateField(default='2020-05-12'),
            preserve_default=False,
        ),
    ]
