# Generated by Django 3.0.4 on 2020-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0008_auto_20200327_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='IN17000', editable=False, max_length=10),
        ),
    ]
