# Generated by Django 3.0.4 on 2020-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0009_auto_20200327_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='INDD830', editable=False, max_length=10, unique=True),
        ),
    ]
