# Generated by Django 3.0.4 on 2020-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0009_auto_20200426_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='children_age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
