# Generated by Django 3.0.4 on 2020-04-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
        ('SalesApp', '0010_auto_20200426_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotehotelinfo',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='QuoteTransferInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.City')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SalesApp.Quote')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Transfer')),
            ],
        ),
    ]
