# Generated by Django 3.0.4 on 2020-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0011_auto_20200331_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='INA670B', editable=False, max_length=10, unique=True),
        ),
    ]
