# Generated by Django 3.0.4 on 2020-04-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
        ('SalesApp', '0011_auto_20200427_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotehotelinfo',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote'),
        ),
        migrations.AlterField(
            model_name='quotetransferinfo',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote'),
        ),
        migrations.CreateModel(
            name='QuoteSightseeingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.City')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote')),
                ('sightseeing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Transfer')),
            ],
        ),
    ]
