# Generated by Django 3.0.4 on 2020-04-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0002_auto_20200424_1437'),
        ('SalesApp', '0012_auto_20200427_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesightseeinginfo',
            name='sightseeing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Sightseeing'),
        ),
    ]
