# Generated by Django 3.0.4 on 2020-04-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0003_auto_20200427_1518'),
        ('SalesApp', '0013_auto_20200427_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteVisaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Destination')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Visa')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteInsuranceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Insurance')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote')),
            ],
        ),
    ]
