# Generated by Django 3.0.4 on 2020-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0013_auto_20200401_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='INF792B', editable=False, max_length=10, unique=True),
        ),
    ]
