# Generated by Django 3.0.4 on 2020-04-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0016_auto_20200428_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteItineraryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote')),
            ],
        ),
    ]
