# Generated by Django 3.0.4 on 2020-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0017_auto_20200402_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='IN87C27', editable=False, max_length=10, unique=True),
        ),
    ]
