# Generated by Django 3.0.4 on 2020-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0017_quoteitineraryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitineraryinfo',
            name='date',
            field=models.DateField(default='2020-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoteitineraryinfo',
            name='ordering',
            field=models.CharField(max_length=255),
        ),
    ]
