# Generated by Django 3.0.4 on 2020-04-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0018_auto_20200402_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='IN26D49', editable=False, max_length=10, unique=True),
        ),
    ]
