# Generated by Django 3.0.4 on 2020-04-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0019_auto_20200430_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteflightinfo',
            name='details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quoteothersinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
