# Generated by Django 3.0.4 on 2020-04-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0021_auto_20200430_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='mark_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
