# Generated by Django 3.0.4 on 2020-04-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0021_auto_20200414_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default='IN5E2DC', editable=False, max_length=10, unique=True),
        ),
    ]
