# Generated by Django 3.0.4 on 2020-04-15 13:40

import SalesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0022_auto_20200415_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='trip_id',
            field=models.CharField(default=SalesApp.models.get_trip_id, editable=False, max_length=10, unique=True),
        ),
    ]
