# Generated by Django 3.0.4 on 2020-04-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0025_auto_20200430_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoteothersinfo',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quotetransportinfo',
            name='type',
            field=models.CharField(choices=[('TRAIN', 'Train'), ('BUS', 'Bus'), ('FERRY', 'Ferry'), ('TAXI', 'Taxi'), ('CAR', 'Self Drive Car Rental')], max_length=100),
        ),
    ]
