# Generated by Django 3.0.4 on 2020-05-01 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0027_auto_20200501_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='inclusions_format',
            field=models.CharField(choices=[('FIXED', 'Fixed Inlusions'), ('CUSTOM', 'Customized Inclusions'), ('FLEXIBLE', 'Full Flexible Format')], default='CUSTOM', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_inclusions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_itinerary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FlexItinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='FlexInclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights', models.TextField(max_length=1000)),
                ('transport', models.TextField(max_length=1000)),
                ('hotels', models.TextField(max_length=1000)),
                ('transfers', models.TextField(max_length=1000)),
                ('sightseeing', models.TextField(max_length=1000)),
                ('visa', models.TextField(max_length=400)),
                ('insurance', models.TextField(max_length=400)),
                ('others', models.TextField(max_length=1000)),
                ('exclusions', models.TextField(max_length=1000)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote')),
            ],
        ),
    ]
