# Generated by Django 3.0.4 on 2020-05-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0028_auto_20200501_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexinclusions',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote'),
        ),
        migrations.AlterField(
            model_name='flexitinerary',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote'),
        ),
    ]
