# Generated by Django 3.0.4 on 2020-05-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0007_auto_20200430_1817'),
        ('SalesApp', '0029_auto_20200501_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteothersinfo',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.City'),
        ),
        migrations.AddField(
            model_name='quoteothersinfo',
            name='type',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
