# Generated by Django 3.0.4 on 2020-05-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0030_auto_20200502_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitineraryinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
