# Generated by Django 3.0.4 on 2020-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0031_auto_20200502_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='children_age',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
