# Generated by Django 3.0.4 on 2020-05-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0013_auto_20200504_1708'),
        ('SalesApp', '0032_auto_20200504_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIXED', 'Fixed Price Package'), ('TEMPLATE', 'Custom Package Template')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('starting_place', models.CharField(max_length=100)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hotel_options', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cities', models.ManyToManyField(to='ContentApp.City')),
                ('destinations', models.ManyToManyField(to='ContentApp.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('order_list', models.TextField(blank=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SalesApp.Package')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SalesApp.Quote')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('TRANSPORT', 'Transport'), ('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('VISA', 'Visa'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=50)),
                ('day_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('airline', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('no_of_rooms', models.PositiveSmallIntegerField()),
                ('price', models.FloatField(default=0)),
                ('optional', models.BooleanField(default=False)),
                ('default_exclude', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.City')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Hotel')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Insurance')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SalesApp.Package')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SalesApp.Quote')),
                ('sightseeing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Sightseeing')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Transfer')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Transport')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Visa')),
            ],
        ),
    ]
