# Generated by Django 3.0.4 on 2020-05-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0034_auto_20200505_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='no_of_rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
