# Generated by Django 3.0.4 on 2020-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0016_auto_20200505_1737'),
        ('SalesApp', '0035_auto_20200505_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inclusion',
            name='day_no',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='other_type',
            field=models.CharField(choices=[('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='sightseeing',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='sightseeing',
            field=models.ManyToManyField(to='ContentApp.Sightseeing'),
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='transfer',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='transfer',
            field=models.ManyToManyField(to='ContentApp.Transfer'),
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='transport',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='transport',
            field=models.ManyToManyField(to='ContentApp.Transport'),
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='visa',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='visa',
            field=models.ManyToManyField(to='ContentApp.Visa'),
        ),
    ]
