# Generated by Django 3.0.4 on 2020-05-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0036_auto_20200505_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inclusion',
            old_name='sightseeing',
            new_name='sightseeings',
        ),
        migrations.RenameField(
            model_name='inclusion',
            old_name='transfer',
            new_name='transfers',
        ),
        migrations.RenameField(
            model_name='inclusion',
            old_name='transport',
            new_name='transports',
        ),
        migrations.RenameField(
            model_name='inclusion',
            old_name='visa',
            new_name='visas',
        ),
    ]
