# Generated by Django 3.0.4 on 2020-05-05 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0038_auto_20200505_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='inclusions_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='package_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_inclusions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='package_itinerary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='package_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='validity_end_date',
            field=models.DateField(default='2021-05-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='validity_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
