# Generated by Django 3.0.4 on 2020-05-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0017_transport_description'),
        ('SalesApp', '0039_auto_20200505_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='package',
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='other_type',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='sightseeings',
            field=models.ManyToManyField(blank=True, to='ContentApp.Sightseeing'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='transfers',
            field=models.ManyToManyField(blank=True, to='ContentApp.Transfer'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='transports',
            field=models.ManyToManyField(blank=True, to='ContentApp.Transport'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='visas',
            field=models.ManyToManyField(blank=True, to='ContentApp.Visa'),
        ),
    ]
