# Generated by Django 3.0.4 on 2020-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0040_auto_20200506_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='item_type',
            field=models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('TRANSPORT', 'Transport'), ('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('VISA', 'Visa'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other'), ('EXCLUSION', 'Exclusion')], max_length=50),
        ),
    ]
