# Generated by Django 3.0.4 on 2020-05-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0041_auto_20200506_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.RemoveField(
            model_name='quotehotelinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='quotehotelinfo',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='quotehotelinfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteinsuranceinfo',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='quoteinsuranceinfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteitineraryinfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quoteothersinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='quoteothersinfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotesightseeinginfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='quotesightseeinginfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotesightseeinginfo',
            name='sightseeing',
        ),
        migrations.RemoveField(
            model_name='quotetransferinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='quotetransferinfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotetransferinfo',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='quotetransportinfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotevisainfo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quotevisainfo',
            name='visa',
        ),
        migrations.DeleteModel(
            name='QuoteFlightInfo',
        ),
        migrations.DeleteModel(
            name='QuoteHotelInfo',
        ),
        migrations.DeleteModel(
            name='QuoteInsuranceInfo',
        ),
        migrations.DeleteModel(
            name='QuoteItineraryInfo',
        ),
        migrations.DeleteModel(
            name='QuoteOthersInfo',
        ),
        migrations.DeleteModel(
            name='QuoteSightseeingInfo',
        ),
        migrations.DeleteModel(
            name='QuoteTransferInfo',
        ),
        migrations.DeleteModel(
            name='QuoteTransportInfo',
        ),
        migrations.DeleteModel(
            name='QuoteVisaInfo',
        ),
    ]
