# Generated by Django 3.0.4 on 2020-05-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0042_auto_20200507_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='min_pax',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
