# Generated by Django 3.0.4 on 2020-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0043_package_min_pax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inclusion',
            old_name='default_exclude',
            new_name='freeze',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='include',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='package_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='item_type',
            field=models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('TRANSPORT', 'Fixed Price Transport'), ('VARIABLE_TRANSPORT', 'Variable Price Transport'), ('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('VISA', 'Visa'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other'), ('EXCLUSION', 'Exclusion')], max_length=50),
        ),
    ]
