# Generated by Django 3.0.4 on 2020-05-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0023_auto_20200508_1525'),
        ('SalesApp', '0044_auto_20200508_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusion',
            name='variable_transports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Variable_Inclusions', to='ContentApp.Transport'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='transports',
            field=models.ManyToManyField(blank=True, related_name='Fixed_Inclusions', to='ContentApp.Transport'),
        ),
    ]
