# Generated by Django 3.0.4 on 2020-05-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0023_auto_20200508_1525'),
        ('SalesApp', '0046_auto_20200508_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.City'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Hotel'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Insurance'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Package'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Quote'),
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='variable_transports',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='variable_transports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Variable_Inclusions', to='ContentApp.Transport'),
        ),
    ]
