# Generated by Django 3.0.4 on 2020-05-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0048_auto_20200511_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='hotel_options',
        ),
        migrations.AddField(
            model_name='hotelgroup',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SalesApp.Package'),
        ),
    ]
