# Generated by Django 3.0.4 on 2020-05-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0049_auto_20200511_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelgroup',
            name='inclusions',
        ),
    ]
