# Generated by Django 3.0.4 on 2020-05-11 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0051_auto_20200511_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='validity_start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
