# Generated by Django 3.0.4 on 2020-05-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0052_auto_20200511_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='mark_up',
            field=models.FloatField(default=0),
        ),
    ]
