# Generated by Django 3.0.4 on 2020-05-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0053_auto_20200512_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='mark_up',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
