# Generated by Django 3.0.4 on 2020-05-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0055_auto_20200512_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
