# Generated by Django 3.0.4 on 2020-05-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0056_quote_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
