# Generated by Django 3.0.4 on 2020-05-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0057_auto_20200512_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
