# Generated by Django 3.0.4 on 2020-05-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0024_auto_20200528_1742'),
        ('SalesApp', '0058_quote_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexitinerary',
            name='quote',
        ),
        migrations.RenameField(
            model_name='inclusion',
            old_name='display_order',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='inclusion',
            old_name='no_of_rooms',
            new_name='itinerary_order',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='checkout_date',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='sightseeings',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='transfers',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='transports',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='variable_transports',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='visas',
        ),
        migrations.AddField(
            model_name='inclusion',
            name='itinerary_inclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='sightseeing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Sightseeing'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Transfer'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Transport'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentApp.Visa'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='item_type',
            field=models.CharField(choices=[('0_FLIGHT', 'Flight'), ('1_HOTEL', 'Hotel'), ('2_TRANSPORT', 'Transport'), ('3_TRANSFER', 'Transfer'), ('4_SIGHTSEEING', 'Sightseeing'), ('5_VISA', 'Visa'), ('6_INSURANCE', 'Insurance'), ('7_OTHER', 'Other'), ('8_EXCLUSION', 'Exclusion')], max_length=50),
        ),
        migrations.DeleteModel(
            name='FlexInclusions',
        ),
        migrations.DeleteModel(
            name='FlexItinerary',
        ),
    ]
