# Generated by Django 3.0.4 on 2020-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0059_auto_20200528_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusion',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
