# Generated by Django 3.0.4 on 2020-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0060_inclusion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusion',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
