# Generated by Django 3.0.4 on 2020-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0061_auto_20200529_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_inclusions',
            new_name='inclusions_exist',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_itinerary',
            new_name='itinerary_exist',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_inclusions',
            new_name='inclusions_exist',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_itinerary',
            new_name='itinerary_exist',
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='date',
        ),
    ]
