# Generated by Django 3.0.4 on 2020-05-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0062_auto_20200529_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='packages',
            field=models.ManyToManyField(to='SalesApp.Package'),
        ),
        migrations.AlterField(
            model_name='inclusion',
            name='include',
            field=models.BooleanField(default=True),
        ),
    ]
