# Generated by Django 3.0.4 on 2020-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0063_auto_20200530_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
