# Generated by Django 3.0.4 on 2020-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0064_quote_manual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price_valid',
            field=models.BooleanField(default=False),
        ),
    ]
