# Generated by Django 3.0.4 on 2020-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0026_auto_20200531_1911'),
        ('SalesApp', '0066_auto_20200530_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.ManyToManyField(to='ContentApp.Tag'),
        ),
        migrations.AddField(
            model_name='package',
            name='themes',
            field=models.ManyToManyField(to='ContentApp.Theme'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(to='ContentApp.Tag'),
        ),
        migrations.AddField(
            model_name='quote',
            name='themes',
            field=models.ManyToManyField(to='ContentApp.Theme'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('NEW', 'New Enquiry'), ('QUOTED', 'Quoted'), ('BOOKED', 'Booked'), ('NOT_CONVERTED', 'Not Converted')], default='NEW', max_length=25),
        ),
    ]
