# Generated by Django 3.0.4 on 2020-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('TRAVELLED', 'Travelled'), ('CLOSED', 'Closed')], default='BOOKED', max_length=25)),
                ('booking_date', models.DateField()),
                ('travel_date', models.DateField()),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('tcs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('commission_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
    ]
