# Generated by Django 3.0.4 on 2020-03-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SalesApp', '0009_auto_20200327_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('TRAVELLED', 'Travelled'), ('CLOSED', 'Closed')], default='BOOKED', max_length=25)),
                ('booking_date', models.DateField()),
                ('travel_date', models.DateField()),
                ('booked_destinations', models.CharField(max_length=256)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('tcs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('commission_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('trip_id', models.CharField(editable=False, max_length=10)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Booking', to='SalesApp.Lead')),
            ],
        ),
    ]
