# Generated by Django 3.0.4 on 2020-03-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(default='TT', max_length=25),
        ),
    ]
