# Generated by Django 3.0.4 on 2020-04-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0001_initial'),
        ('OperationsApp', '0002_auto_20200421_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bookings', to='ProfilesApp.Staff'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, related_name='AssignedBookings', to='ProfilesApp.Staff'),
        ),
    ]
