# Generated by Django 3.0.4 on 2020-03-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsApp', '0002_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(default='TT', editable=False, max_length=25),
        ),
    ]
