# Generated by Django 3.0.4 on 2020-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsApp', '0003_auto_20200331_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(default='TT', max_length=25),
        ),
    ]
