# Generated by Django 3.0.4 on 2020-05-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsApp', '0004_auto_20200512_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_destinations',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
    ]
