# Generated by Django 3.0.4 on 2020-03-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsApp', '0004_auto_20200331_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='source',
        ),
    ]
