# Generated by Django 3.0.4 on 2020-05-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContentApp', '0023_auto_20200508_1525'),
        ('OperationsApp', '0005_auto_20200512_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('passport_num', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issue_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='itinerary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FLIGHT', 'Flights'), ('HOTEL', 'Hotels'), ('TRANSPORT', 'Transport'), ('TRANSFER', 'Transfer'), ('SIGHTSEEING', 'Sightseeing'), ('VISA', 'Visa'), ('INSURANCE', 'Insurance'), ('OTHER', 'Others'), ('EXCLUSION', 'Exclusions')], max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_limit', models.DateField(blank=True, null=True)),
                ('conf_status', models.CharField(choices=[('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('CONFIRMED', 'Confirmed')], max_length=50)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ContentApp.Vendor')),
            ],
        ),
    ]
