# Generated by Django 3.0.4 on 2020-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsApp', '0007_bookingitem_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='conf_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BLOCKED', 'Blocked'), ('CONFIRMED', 'Confirmed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
