# Generated by Django 3.0.4 on 2020-05-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationsApp', '0008_auto_20200513_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
