# Generated by Django 3.0.4 on 2020-05-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0065_quote_price_valid'),
        ('OperationsApp', '0009_bookingitem_display_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='detail',
            new_name='display_handle',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='display_order',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='inclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SalesApp.Inclusion'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='item_type',
            field=models.CharField(choices=[('0_FLIGHT', 'Flight'), ('1_HOTEL', 'Hotel'), ('2_TRANSPORT', 'Transport'), ('3_TRANSFER', 'Transfer'), ('4_SIGHTSEEING', 'Sightseeing'), ('5_VISA', 'Visa'), ('6_INSURANCE', 'Insurance'), ('7_OTHER', 'Other'), ('8_EXCLUSION', 'Exclusion')], max_length=50),
        ),
    ]
