# Generated by Django 3.0.4 on 2020-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilesApp', '0003_auto_20200530_1618'),
        ('OperationsApp', '0010_auto_20200530_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traveler',
        ),
        migrations.AddField(
            model_name='booking',
            name='travelers',
            field=models.ManyToManyField(to='ProfilesApp.Traveler'),
        ),
    ]
